version: "3.2"

# This is the file for a deployed server.
# Domain names can be customized in the .env file.
# This assumes you have already set up certificates via Let's Encrypt for the domain.
# Since that is a manual step, we don't have it checked in here.
# https://pentacent.medium.com/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71
# is the guide we used to set that up initially.
services:
  db:
    restart: unless-stopped
    network_mode: bridge

  # service configuration for our dockerized Rails app
  app:
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: staging.cobr.ai
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: staging.cobr.ai
      LETSENCRYPT_EMAIL: website@nisei.net

    network_mode: bridge
    # expose the port we configured Unicorn to bind to
    expose:
      - "3000"

    volumes:
      - cobra-logs:/var/www/cobra/log

volumes:
    cobra-assets:
    cobra-logs:
