services:
  # service configuration for our dockerized Rails app
  app:

    # use the Dockerfile next to this file
    build: .

    # sources environment variable configuration for our app
    env_file: .env

    depends_on: 
      - db

    restart: always

    # rely on the RAILS_ENV value of the host machine
    environment:
      - POSTGRES_PASSWORD
      - RAILS_ENV

    volumes:
      - ./config/database.yml:/var/www/cobra/config/database.yml
      - cobra-logs:/var/www/cobra/log
      - cobra-tmp:/var/www/cobra/tmp
      - .:/var/www/cobra/

  # service configuration for our database
  db:
    # use the preferred version of the official Postgres image
    # see https://hub.docker.com/_/postgres/
    image: postgres:14.5-alpine

    env_file: .env

    environment:
      - POSTGRES_PASSWORD

    # persist the database between containers by storing it in a volume
    volumes:
      - cobra-postgres:/var/lib/postgresql/data
      - ./postgres-docker-init.sql:/docker-entrypoint-initdb.d/postgres-docker-init.sql

volumes:
  cobra-logs:
  cobra-postgres:
  cobra-tmp:
