version: "3.2"

services:
  # service configuration for our dockerized Rails app
  app:

    # use the Dockerfile next to this file
    build: .

    # sources environment variable configuration for our app
    env_file: .env

    # rely on the RAILS_ENV value of the host machine
    environment:
      - POSTGRES_PASSWORD
      - RAILS_ENV

    # makes the app container aware of the DB container
    links:
      - db

    volumes:
      - .:/var/www/cobra/
      - cobra-logs:/var/www/cobra/log
      - cobra-assets:/var/www/cobra/public/assets
      - cobra-tmp:/var/www/cobra/tmp

  # service configuration for our database
  db:
    # use the preferred version of the official Postgres image
    # see https://hub.docker.com/_/postgres/
    image: postgres:9

    env_file: .env

    environment:
      - POSTGRES_PASSWORD

    # persist the database between containers by storing it in a volume
    volumes:
      - cobra-postgres:/var/lib/postgresql/data

volumes:
  cobra-assets:
  cobra-logs:
  cobra-postgres:
  cobra-tmp:
