version: "3.2"

# This is the file for a deployed server.
# Domain names can be customized in the .env file.
# This assumes you have already set up certificates via Let's Encrypt for the domain.
# Since that is a manual step, we don't have it checked in here.
# https://pentacent.medium.com/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71
# is the guide we used to set that up initially.
services:
  db:
    restart: unless-stopped
    networks:
      - backend

  # service configuration for our dockerized Rails app
  app:
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: $COBRA_DOMAIN
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: $COBRA_DOMAIN
      LETSENCRYPT_EMAIL: website@nisei.net

    networks:
      - backend
      - null_signal
    # expose the port we configured Puma to bind to
    expose:
      - "3000"

networks:
  backend:
  null_signal:
    external: true
