version: "3.3"

services:
  # service configuration for our dockerized Rails app
  app:
    # expose the port we configured Unicorn to bind to
    expose:
      - "3000"

    volumes:
      - cobra-logs:/var/www/cobra/log

  # service configuration for our web server
  web:
    # set the build context to the root of the Rails app
    build:
      context: .
      # build with a different Dockerfile
      dockerfile: config/containers/Dockerfile-nginx

    # makes the web container aware of the app container
    links:
      - app

    # expose the port we configured Nginx to bind to
    ports:
      - "80:80"

    volumes:
      - cobra-logs:/var/www/cobra/log
        #    volumes_from:
        #      - app
        #
volumes:
    cobra-logs:
