default: &default
  adapter: postgresql
  encoding: unicode
  database: cobra
  username: cobra
  password: cobra
  host: do-not-resolve

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
