# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55ca41d1c22ee9842aeef2aa5641c063f369e142723586958bd3b36921ca7026bdbf8b98a78376510bd351f790ed99c308e8cf5633b6e4ac678a0e8ef998f6dc
  abr_auth: ABRAUTH
  # In order to support multiple serving domains, specify NRDB credentials under a given hostname.
  # You may specify multiple hostnames.
  localhost:
    nrdb:
      client_id: 17_68q8wwxa2bs4ws0gk4o8wcoo4k8cgk80o8s0kggcsggcww4o48
      client_secret: 11wixjjki6u8g4kkkss4ksog4gosowg4wswksko48c0gwwc0s
      redirect_uri: http://localhost:3000/oauth/callback

test:
  secret_key_base: ca42a8b2b1bb239b0350258a65bfb3e66c5f636ddc08f7d8a239aa7a10806e12a0390fc0a61835e31fa0971a93f7eab59b2a24c2ea23d16a4b125d4c4793f4e4
  abr_auth: ABRAUTH
  localhost:
    nrdb:
      client_id: test_id
      client_secret: test_secret
      redirect_uri: http://localhost:3000/oauth/callback

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  abr_auth: <%= ENV["ABR_AUTH"] %>
  # In order to support multiple serving domains, specify NRDB credentials under a given hostname.
  # You may specify multiple hostnames.
  <%= ENV["COBRA_DOMAIN"] || "cobr.ai" %>:
    nrdb:
      client_id: <%= ENV["NRDB_CLIENT"] %>
      client_secret: <%= ENV["NRDB_SECRET"] %>
      redirect_uri: https://<%= ENV["COBRA_DOMAIN"] || "cobr.ai" %>/oauth/callback

